language: node_js
node_js:
  - lts/*


before_install:
- pip install --user awscli
- npm install -g yaml-lint

jobs:
  include:
    - stage: validate yaml
      script: yamllint src/conferences.yml
    - stage: build
      script:
      - mkdir publish
      - npm install
      - npm run build
      - cp -R index.html thank-you.html dist static publish
    - stage: deploy
      deploy:
        on:
          branch: master
        provider: s3
        bucket: www.gotodevops.org
        access_key_id: $AWS_ACCESS_KEY_ID
        secret_access_key: $AWS_SECRET_ACCESS_KEY
        region: us-west-2
        acl: public_read
        skip_cleanup: true
        local_dir: ./publish
      after_deploy:
      - aws configure set preview.cloudfront true
      - aws cloudfront create-invalidation --distribution-id $WWW_CLOUDFRONT_DISTRIBUTION_ID --paths "/*"
      - aws cloudfront create-invalidation --distribution-id $NON_WWW_CLOUDFRONT_DISTRIBUTION_ID --paths "/*"
